<?php

if (1==2) {
//Database en hostinger
$username = "u887045922_vamosba";
$password = "Carlosyana_99";
$database = "u887045922_vamosba";
$server = "185.201.11.107";

//MYSQL en AWS con IP
$username = "test";
$password = "isO04JyQwsDUm83O";
$database = "vamosba";
$server = "3.138.102.101";

}

//MYSQL en AWS con localhost
$username = "test";
$password = "isO04JyQwsDUm83O";
$database = "vamosba";
$server = "localhost";


?>