
<div class="container" style="background-color:#FFFFFF;" >
	<div class="row" style="background-color:#FFFFFF;">
		
		<div class="col-sm-12 col-md-12 col-lg-12" align="right"> 
			<div class="fb-like" data-href="https://topbuenosaires.online" data-layout="button_count" data-action="like" data-size="small" data-show-faces="true" data-share="true">
			</div>
		</div>
	</div>
</div>

<br>

<div class="container" style="background-color:#137791;" >
	<div class="row" >
		<div class="col-sm-6 col-md-4 col-lg-4" align="left"> 
			<br>
		</div>
	</div>
</div>


<div class="container" style="background-color:#fafafa;" >

<div id="footer">
	<div class="footer-contents">
		<div class="legal">
			<a href="politica_privacidad.php"><font size="1" face="helvetica" color="blue">Política de privacidad</a> 
			| <a href="aboutus.php"><font size="1" face="helvetica" color="blue">Acerca de nosotros</a>   
          	<br>
			<font size="1" face="helvetica" color="black"><small>&copy; 2021 Todos los derechos reservados .</p>
			<img src="images/app/utils/email-24px.svg"  height="24" width="24"  alt="" longdesc="">buenosairestopinfo@gmail.com
			&nbsp;&nbsp;&nbsp;
			</small><a href="mailto:buenosairestopinfo@gmail.com" target="_blank" class="btn btn-primary">Email Us</a>
			</font>
		</p>
			<a href="https://api.whatsapp.com/send?phone=+541127835577&text=Hola quiero contactarlos sobre una publicación en *https://topbuenosaires.online*." target="blank" >
				<img src="images/app/utils/whatsapp_ico.png"  height="22" width="22">Escribenos por whatsapp</a><br>
			<br><br><br><br><br><br>
			<hr>	
		</div>
     </div>
</div> 
</div>