


<br>

<div class="container" style="background-color:#137791;" >
	<div class="row" >
		<div class="col-sm-6 col-md-4 col-lg-4" align="left"> 
			<br>
		</div>
	</div>
</div>


<div class="container" style="background-color:#fafafa;" >

<div id="footer">
	<div class="footer-contents">
		<div class="legal">
		<font size="1" face="helvetica" color="black"><small>&copy; 2021 Todos los derechos reservados .</p>
		<br><br><br><br><br><br>
			<hr>	
		</div>
     </div>
</div> 
</div>