<div class="container-fluid" style="background-color:#FBFCFC;" >
	<div class="row">
		<div class="col-sm-6 col-md-8 col-lg-8"> 
		  	<img src="imagenes/apps/logo2.jpg"  alt="" longdesc="" id="img_logo" height="42" width="82">
			
		</div>
		<div class="col-sm-6 col-md-4 col-lg-4" align="right">
			
			<font size="1" face="arial" color=white><b>email:</b>buai@gmail.com</font>
			</div>
	</div>
</div>

<div class="container-fluid" style="background-color:#FAFAFA;" >
	<div class="row" style="background-color:#086A87;">
		<div class="col-sm-8" align="left" > 
			<button type="button" class="btn btn-success"  onclick="location.href='http://www.vamosba.com';">Inicio</button>
			<!--<button type="button" class="btn btn-warning" onclick="location.href='/guia/listado23.php?categoria=I000';" target="_self" >De interés</button>-->
			<button type="button" class="btn" onclick="location.href='aboutus.php';">Quienes somos</button>
			<!--<button type="button" class="btn btn-info" onclick="location.href='form_contacus.php';">Contactonos</button>-->
			
		</div>
	</div>
</div>



