<div class="container-fluid" style="background-color:#FBFCFC;" >
	<div class="row">
		<div class="col-sm-6 col-md-8 col-lg-8"> 
	<!--	  	<img src="imagenes/apps/logo2.jpg"  alt="" longdesc="" id="img_logo" height="42" width="82">
	-->
		</div>
		<div class="col-sm-6 col-md-4 col-lg-4" align="right">
			
			<font size="1" face="arial" color=white><b>email:</b>buai@gmail.com</font>
			</div>
	</div>
</div>

<div class="container-fluid" style="background-color:#FAFAFA;" >
	<div class="row" style="background-color:#cfcfcf;">
		<div class="col-sm-8" align="left" > 
			
		</div>
	</div>
</div>



